[core]
workspace_base="./workspace"
debug=true

[llm.qwen3]
model="openai/Qwen/Qwen3-8B"
api_key="aditya_vllm"
base_url="http://127.0.0.1:2339/v1"
disable_vision=true
caching_prompt=false
log_completions=true
temperature=0.6
top_p=0.95
top_k=20

[llm.qwen2_5]
model="openai/Qwen/Qwen2.5-Coder-7B-Instruct"
api_key="aditya_vllm"
base_url="http://127.0.0.1:2339/v1"
disable_vision=true
caching_prompt=false
log_completions=true

[llm.llama3]
model="openai/meta-llama/Llama-3.1-8B-Instruct"
api_key="aditya_vllm"
base_url="http://127.0.0.1:2339/v1"
disable_vision=true
caching_prompt=false
log_completions=true

[llm.gemma3]
model="openai/google/gemma-3-12b-it"
api_key="aditya_vllm"
base_url="http://127.0.0.1:2339/v1"
disable_vision=true
caching_prompt=false
log_completions=true
temperature=1
top_p=0.95
top_k=64