model: Qwen/Qwen2.5-Coder-7B-Instruct
host: "127.0.0.1"
port: 2339
uvicorn-log-level: "critical"
api-key: "aditya_vllm"
gpu-memory-utilization: 0.8
tokenizer: Qwen/Qwen2.5-Coder-7B-Instruct
tensor-parallel-size: 4
enable-auto-tool-choice: true
tool-call-parser: hermes